services:
  pulsebox:
    image: ramtinboreili/pulsebox:v0.0.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #environment:
      #- LOG_LEVEL=debug
    ports:
      - "8037:8080"
    stdin_open: true
    tty: true
